version: '3.8'
services:
    frontend: 
        build:
            context: ./Frontend/Curriculums
            dockerfile: Dockerfile
        ports:
            - 5173:5173
        depends_on:
            - backend
        networks:
            - app_network

    backend:
        build:
            context: ./Backend/Curriculos
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        networks:
            - app_network
networks:
    app_network:
        driver: bridge